# frozen_string_literal: true

require_relative 'models/timetable'
require_relative 'models/timetable_list'
require_relative 'models/dry_result_forme_wrapper'
require_relative 'models/days_of_the_week'
require_relative 'models/schema_types'
require_relative 'models/schema_delete'
require_relative 'models/store'
require_relative 'models/schema_new_item'
require_relative 'models/schema_for_week'
require_relative 'models/schema_retake'
require_relative 'models/schema_question'
require_relative 'models/schema_load'
require_relative 'models/schema_move'
