# frozen_string_literal: true

require_relative 'models/timetable'
require_relative 'models/timetable_list'
require_relative 'models/dry_result_forme_wrapper'
require_relative 'models/days_of_the_week'
require_relative 'models/schema_types'
require_relative 'models/delete_schema'
require_relative 'models/store'
require_relative 'models/new_item_schema'
require_relative 'models/for_week_validation_schema'
require_relative 'models/retake_schema'
require_relative 'models/question_schema'
require_relative 'models/load_schema'
require_relative 'models/move_schema'
